version: '3.9'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    # environment:
    #   - WDS_SOCKET_HOST=127.0.0.1 
    #   - CHOKIDAR_USEPOLLING=true
    #   - WATCHPACK_POLLING=true
    env_file:
        - .env
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes: 
      - redis:/data
volumes:
  redis:
    driver: local